### ISSUE TITLE
Skip back in video when annotation or question specifies it

### ISSUE THREAD

**Issue by HarryCutts** [soton-ecs-2014-gdp-12/videogular-questions#1]
An annotation or a question should be able to force the user to skip to another location in the video according to the user's response. For example, a skip might be forced when:
- The user answers (any|all|a number of) question(s) incorrectly
- The user clicks an "I don't understand" button, or similar

A decision must be reached on what use cases we're going to support, and those use cases should then be implemented.

**Comment by samuelbennett** [comment]
1.5
