### ISSUE TITLE
CSS display of the questions needs to be improved

### ISSUE THREAD

**Issue by chewett** [soton-ecs-2014-gdp-12/videogular-questions#2]
The current display of the questions is very basic, not using any styling, this can be improved for a better user experience.

**Comment by samuelbennett** [comment]
1

**Comment by samuelbennett** [comment]
Don't forget about disabled buttons

**Comment by samuelbennett** [comment]
This is very much linked #16 and #17

**Comment by chewett** [comment]
Disabled buttons now look very much disabled due to bootstrap.

**Comment by chewett** [comment]
Bootstrap have provided us a colour pallette, waiting for implementation of the back end properly to restyle and semantic'i'fy the HTML nicely.
