### ISSUE TITLE
WebWorker breaks due to lack of `console` on Firefox 25

### ISSUE THREAD

**Issue by HarryCutts** [soton-ecs-2014-gdp-12/videogular-questions#21]
In Firefox 25, WebWorker scripts cannot access the `console` object. This means that it errors when it tries to display a question, and the question doesn't pop up.

**Comment by marialynch23** [comment]
0.5

**Comment by HarryCutts** [comment]
Commit 6465540 actually broke all `console.log`s due to some weirdness with the console in web workers. Commit ddc5dbb removes the stub, along with the last `console.log` statement. JSHint should complain if `console` is used in the web worker anyway, so I think we should just not commit `console` lines.
