### ISSUE TITLE
Error when you switch example

### ISSUE THREAD

**Issue by cbaines** [soton-ecs-2014-gdp-12/videogular-questions#34]
If you load http://localhost:8000/app/#/caesar-example then click on simple example and play the video, things break.

Error: [$compile:ctreq] Controller 'videogular', required by directive 'vgQuestionSingle', can't be found!

**Comment by cbaines** [comment]
Believe I might have fixed this in 3bfa2f65b40a755fc7998b9a638598b253425c3a , but I still do not know why the problem only appears sometimes...

**Comment by cbaines** [comment]
@samuelbennett See above ^ before you attempt to reproduce this.

**Comment by samuelbennett** [comment]
You are right. That fixes the issue. I have done some investigation in to why we got the error, but not a huge amount to report.
It is pretty easy to see why your changes would fix that error though.
