### ISSUE TITLE
handlers is not a function

### ISSUE THREAD

**Issue by chewett** [soton-ecs-2014-gdp-12/videogular-questions#37]
Error:

TypeError: handlers[key][i] is not a function

in file: questions.js:28

steps to reproduce:
Go to authoring tool
Create a question set with 1 multiple choice question and one rating question
It will fail when it loads up the rating question

**Comment by cbaines** [comment]
Worked around in 8f075291cd7d947f1c4f32afccac2bf9f41c3228
