### ISSUE TITLE
Questions do not show again if the video is rewinded

### ISSUE THREAD

**Issue by marialynch23** [soton-ecs-2014-gdp-12/videogular-questions#7]

**Comment by samuelbennett** [comment]
To me this issue seems to be more broad. Our thoughts about how rewinding and skiping interacts with different levels of question setups and "strictness" needs to formalised

**Comment by samuelbennett** [comment]
1.5

**Comment by chewett** [comment]
Design decision, we have chosen not to do this currently. Could be implemented later as an extension
