### ISSUE TITLE
User can still skip using Videogular controls when the overlay is displayed

### ISSUE THREAD

**Issue by HarryCutts** [soton-ecs-2014-gdp-12/videogular-questions#9]
To reproduce:
1. Open the example page and play the video until the overlay pops up.
2. Click on the video controls below the overlay. The play/pause button and scrub bar can still be used.

**Comment by samuelbennett** [comment]
1

**Comment by chewett** [comment]
Basic resolution in: https://github.com/soton-ecs-2014-gdp-12/videogular-questions/commit/659a5068f5d8ed61c7b6f8d6904a6d4c19d66abe
